---
title: Statistisches Praktikum WiSe21/22, Trendschä̈tzung DAS-Monitoring
author: Sven Maurice Morlock, Tina Drazevic, Xinyang Chen, Tim Baurtoth
institute: Ludwig-Maximilians-Universität München, Institut für Statistik
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: 
  beamer_presentation:
    theme: "Montpellier"
    latex_engine: xelatex
---

# Datensatz und Aufgabenstellung

## Allgemeines

- Einlesen der Daten aus Excel files
- automatisierte Verarbeitung
- Zähldaten vs. Metrische Daten
- Trendschätzung und Trendtest

# Methoden

## Trendschätzung Probleme
- Extremwerte
- Varianzstruktur
- geringe Anzahl Beoachtungen

## Trendschätzung
- soll nicht paramtetisch sein
- Bayesian Splines vorzuziehen wegen Varianzstruktur 
- Siehe Kauermann et al.: Filtering Time Series with Penalized Splines
- Alternativ Filtertechniken aus dem Bereich Signal Processing mit R packages (mFilter)

## Trendtest
- Mann-Kendall Trendtest implementiert in package 'Kendall'
- Ausgabe: Kendalls rho und p-Value zu $H_{0}$:kein Trend

## Unsere aktuellen Probleme
- Zusammenfassen der Indikatoren (50 Stück mit meherern Zeitreihen)
- Viele Möglichketen zur Trendschätzung, 
- Mehrere R-packages wie 'forecast', und 'fpp3' um Trend zu filtern
- Idee in den Packeten ist aber mehr Trend + Seasonale Komponente +Zyklischekomponente
- Für uns mehr von Interesse: Trend + Extremwerkomponente + Zyklischekomponente
- Siehe Kauermann et. al. 2011

## Literatur
- Kauermann, G., Krivobokova, T., Semmler, W. (2011) Filtering time series with penalized splines. Studies in Nonlinear Dynamics & Econometrics.
- Mudelsee, M. (2013) Climate Time Series Analysis, Springer Verlag